language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

# Move to the actual Android dir
before_install:
    - cd lib/Adn/
