language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-19

before_install:
    - cd lib/Adn/
    - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ./wait_for_emulator
  - adb shell input keyevent 82 &
